# TODO
# 1. Determine the base requirements for mem etc for running crush ans set them in the compose file
# 2. Determine how to have the Sophos endpoint protection check all incoming and outgoing files
version: '3.7'

services:
  crushftp:
    build:
      context: ./crushftp
      dockerfile: Dockerfile
    image: crushftp:0.0.1
    volumes:
      # Persist user changes outside the container
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/shared-volumes/crushftp-vol1/users
        target: /var/opt/CrushFTP9/users
      # Persist job changes outside the container
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/shared-volumes/crushftp-vol1/jobs
        target: /var/opt/CrushFTP9/jobs
      # Persist ackups changes outside the container
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/shared-volumes/crushftp-vol1/backup
        target: /var/opt/CrushFTP9/backup
      # # Persist preference changes outside the container
      # - type: bind
      #   source: /mnt/swarm-shared/joncatlin-development/shared-volumes/crushftp-vol1/prefs.XML
      #   target: /var/opt/CrushFTP9/prefs.XML
    ports:
      - target: 21
        published: 21
      - target: 443
        published: 443
      - target: 2222
        published: 2222
      - target: 8080
        published: 8080
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: all
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - crushftp

networks:
  crushftp:
